### ISSUE TITLE
The Application Default Credentials are not available

### ISSUE THREAD

**Issue by Raviraj20** [googleapis/gax-dotnet#175] opened 2017-05-05 08:34 UTC
Getting an similar error when using an .Net
Can someone help how to solve this error

Message":"An error has occurred.","ExceptionMessage":"The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.","ExceptionType":"System.InvalidOperationException","StackTrace":" at Google.Api.Gax.TaskExtensions.WaitWithUnwrappedExceptions(Task task)\r\n at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint

**Comment by jskeet** [comment] 2017-05-05 13:26
We can't really help without more context:

- Where are you running this code? (On GCP in some form, or not?)
- Do you have the `GOOGLE_APPLICATION_CREDENTIALS` environment variable assigned a value?
- If not, have you logged in with `gcloud auth application-default login`?

Basically, we need to know how you *expect* to authenticate in order to find out why it's not working.

**Comment by Raviraj20** [comment] 2017-05-08 12:05
@jskeet 
thanks for replying 
i have set GOOGLE_APPLICATION_CREDENTIALS environment variable assigned  
and done  gcloud auth application-default login 


but 
GoogleCredential credential = await GoogleCredential.GetApplicationDefaultAsync(); 
this line gives compilation error  when i tye this

**Comment by jskeet** [comment] 2017-05-08 12:47
Well what's the compilation error, and is this within an async method? (If not, I'd expect it to fail for that reason.)

Again, please give us details of the context in which the code is running - there isn't really enough information for us to help you at the moment.

**Comment by Raviraj20** [comment] 2017-05-08 12:50
@jskeet  its showing me this error 




![image](https://cloud.githubusercontent.com/assets/25105115/25804859/fad9cb3c-341a-11e7-90a2-d85cf74e433e.png)

**Comment by jskeet** [comment] 2017-05-08 12:53
Right, yes - that's got nothing to do with the library, and everything to do with how async/await works. You can't use `await` outside an asynchronous method or anonymous function.

Now it's not clear why you're calling this at all - we still don't know which API you're trying to use, or how. Given your screenshot, presumably you're writing a WebAPI application, but we don't know which version of the framework you're targeting, or the way you're running your code when it fails. (Does it work when debugging locally, but fail on a server, for example?)

**Comment by Raviraj20** [comment] 2017-05-08 12:59
yup I m writing an web Api 
which will internaly called the google could api 
i m using a .net framework 4.5 

frist i have make a simple program 
![image](https://cloud.githubusercontent.com/assets/25105115/25805119/18d3c3b2-341c-11e7-8c0f-a86ff0dde427.png)


its woked for me but when i am hosting my Api and calling it from different PC then its gives error 

but if i m using it in  a local maching with out hosting its work fine

**Comment by Raviraj20** [comment] 2017-05-08 13:06
@jskeet 
yess it work when debugging locally, but fail on a server, for example?)
when i use this code 
![image](https://cloud.githubusercontent.com/assets/25105115/25805397/1c410824-341d-11e7-8f9f-fe68be517bd1.png)

**Comment by jskeet** [comment] 2017-05-08 13:53
It would be helpful if you'd post code - and stack traces - as *text* rather than images. It's a lot easier to read that way.

It sounds like you just need to set `GOOGLE_APPLICATION_CREDENTIALS` on your server, in the system environment variables, and make sure the service account JSON file is accessible to the hosting process.

**Comment by Raviraj20** [comment] 2017-05-08 16:51
yup I  have set GOOGLE_APPLICATION_CREDENTIALS on  server, in the system environment variables, and the service account JSON 

here my code 
its work fine when i m using it in a local maching  its work fine

when i am hosting my Api and calling it from different PC then its gives error
and saying
 public class PansLogic1
    {
      //  string[] words;
        string img = " ";
        int total;
      
        public void PanDetails()
        {
       
            var client = ImageAnnotatorClient.Create();
            //// Load the image file into memory
            var image = Image.FromFile("12.jpg");
            //// Performs label detection on the image file
            var response = client.DetectText(image);
            string s = response[0].Description;
              }
     }

**Comment by jskeet** [comment] 2017-05-08 16:59
Could you just check that you can *fetch* the environment variable within your code first? My guess is that it's really *not* set - otherwise I would expect you to get a different error.

**Comment by Raviraj20** [comment] 2017-05-08 17:01
ya i have set GOOGLE_APPLICATION_CREDENTIALS 
with credential.json in classpath

**Comment by Raviraj20** [comment] 2017-05-08 17:01
how can i fetch the environment variable within your code in my project

**Comment by Raviraj20** [comment] 2017-05-08 17:03
how can i fetch the environment variable within   code in my project

**Comment by jskeet** [comment] 2017-05-08 17:03
Just call `string value = Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS);`

Log that, or return it as a value just in a test API...

**Comment by Raviraj20** [comment] 2017-05-08 17:08
yup i m able to access that 
 fetch the environment variable within my  code ![image](https://cloud.githubusercontent.com/assets/25105115/25815629/eff29a72-343e-11e7-853b-676e83159100.png)

**Comment by jskeet** [comment] 2017-05-08 17:14
But that's showing a debugger, so it's presumably not on the machine where things aren't working. Return that in another API method, and try it *in the same environment where the credentials fail*.

**Comment by Raviraj20** [comment] 2017-05-08 17:22
ok 
in my code  
i am using a string variable value  which stores the path of creadential.json file 

so where should i user this value   variable in  my code


 
  public class PansLogic1
    {

        public void PanDetails()
        {
            string value = Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS");**

            PanGS p = new PanGS();
            var client = ImageAnnotatorClient.Create();
            //// Load the image file into memory
            var image = Image.FromFile("12.jpg");
            //// Performs label detection on the image file
            var response = client.DetectText(image);
            string s = response[0].Description;
}

**Comment by Raviraj20** [comment] 2017-05-08 17:24
now i m getting a different error 


{"Message":"An error has occurred.","ExceptionMessage":"Could not find file 'c:\\windows\\system32\\inetsrv\\12.jpg'.","ExceptionType":"System.IO.FileNotFoundException","StackTrace":" at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)\r\n at Google.Cloud.Vision.V1.Image.FromFile(String path)\r\n at

**Comment by jskeet** [comment] 2017-05-08 17:29
Remove *all the Image API code*. Just make your WebAPI return the value of the environment variable. That's all we're trying to do at the moment. Please focus on one thing at a time.

**Comment by Raviraj20** [comment] 2017-05-08 17:40
@jskeet
 just say me one thing that 
 WebAPI return the value of the environment variable and we are storing it in value 
so where to use value again

**Comment by jskeet** [comment] 2017-05-08 17:42
You haven't shown a WebAPI returning the environment variable. You've shown your code calling `Environment.GetEnvironmentVariable`, but you *haven't* shown a WebMethod returning that. Once you've got one, just hit the WebAPI (running on the server with problems) with a browser, so you can see what value is returned.

**Comment by Raviraj20** [comment] 2017-05-08 17:42
ok let me try this

**Comment by Raviraj20** [comment] 2017-05-09 09:34
@jskeet 
thanks
 alot final its get slove

**Comment by jskeet** [comment] 2017-05-09 09:35
Sorry, I'm afraid I don't understand that comment...

**Comment by Raviraj20** [comment] 2017-05-09 09:39
@jskeet 
I m saying 
finaly issuse get slove with the help of your

so Thank you

**Comment by jskeet** [comment] 2017-05-09 09:40
Ah, you mean *solved*? Great - closing the issue then.

**Comment by shivp** [comment] 2018-05-27 12:27
I am facing the same issue. I have set the environment variable on the production server. I have checked whether the value is accessible using by running an windows exe that fetches the environment variable value, on the production server. I have give access to "Everyone" group on the folder where the credentials JSON file resides. It worked on our network server by setting the permissions. But it does not work on the production server.  The error description isn't very helpful. The same error message was showing when there was a mismatch in the versions of the Newtonsoft.Json dll. I have added the assembly binding redirects in web.config file. @Raviraj20, can you please elaborate on what solution you applied ?

**Comment by farhatkhan** [comment] 2018-07-11 13:01
@Raviraj20 

How can you set the environmental path for google credentials?
I am facing the same issue. Please tell me the complete code.

Thanks

**Comment by jskeet** [comment] 2018-07-11 13:08
@farhatkhan: You wouldn't normally set the environment variable with *code* - you'd do it however you set up the environment variable elsewhere. Without any more information on where you're running our code or what you've tried, there's not a lot more we can say.

**Comment by jskeet** [comment] 2018-07-11 13:30
So *have* you set the GOOGLE_APPLICATION_CREDENTIALS environment variable to refer to a file containing service account credentials? How have you done so, and how are you running the code? Note that if you set the environment variable system-wide after launching VS, that may well not "notice" the change, but restarting VS should help.

**Comment by farhatkhan** [comment] 2018-07-11 13:34
I don't know where set the environmental path. Can you guide me step by step?

**Comment by jskeet** [comment] 2018-07-11 13:43
See https://cloud.google.com/docs/authentication/getting-started - for how to set it in a particular console session, or from the [Microsoft documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682653(v=vs.85).aspx)

>  You can also view or modify the environment variables by selecting System from the Control Panel, selecting Advanced system settings, and clicking Environment Variables.

**Comment by farhatkhan** [comment] 2018-07-11 13:51
I have set environmental path : control panel-> environment->advanced->Environmental Variable->New->Browse json file and set it name. then press ok

Now how to set in c#?

**Comment by jskeet** [comment] 2018-07-11 13:53
@farhatkhan: You don't *set* it in C#. The library will pick it up automatically.

If you've already set the variable via control panel, and restarted Visual Studio since setting it, it should already work. If you're still getting this error, then one simple way of debugging it is to print out the environment variable value:

```csharp
string credentialPath = Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS");
Console.WriteLine(credentialPath);
```

Check the value that prints out. If it's not printing out the filename you expect, double check control panel.

**Comment by farhatkhan** [comment] 2018-07-11 14:20
string credentialPath = Environment.GetEnvironmentVariable("googlecloudvision");
Console.WriteLine(credentialPath);
C:\Users\Administrator\Desktop\OCRTestImage\My Project-d424b41c7b5b.json
it send me proper path. but face again same issue on var client = ImageAnnotatorClient.Create();
The Application Default Credentials are not available. They are available if running in Google Compute Engine.

**Comment by jskeet** [comment] 2018-07-11 14:21
Why are you asking for an environment variable called `googlecloudvision`? The environment variable is meant to be `GOOGLE_APPLICATION_CREDENTIALS`, as per the error message.

**Comment by farhatkhan** [comment] 2018-07-11 14:45
Now error comes at :var response = client.DetectText(image);
Additional information: Status(StatusCode=PermissionDenied, Detail="This API method requires billing to be enabled. Please enable billing on project #1077400448068 by visiting

**Comment by jskeet** [comment] 2018-07-11 14:50
Okay, so that sounds like a very different problem - that perhaps you haven't enabled billing. I suggest you look into it, and raise a new issue if necessary.

**Comment by kazmi1215** [comment] 2018-10-08 15:58
Hi,

I am a beginner in this field. I just want to read text from a picture but its giving me error. What should I do? I will really appreciate the help. Thank you
![code](https://user-images.githubusercontent.com/26508892/46619939-0e142180-cb2c-11e8-8d5a-64f75650da5e.JPG)
![error](https://user-images.githubusercontent.com/26508892/46619941-0e142180-cb2c-11e8-9653-ec8cdb79fec1.JPG)

**Comment by jskeet** [comment] 2018-10-08 16:02
Well it sounds like you'd already got past that in your previous comment - you were making a call to the API, but you didn't have a billing account associated with your Cloud project. So go back to whatever you were doing before, but after fixing the project.

Anything I'd write in very general terms would be the same as is written at https://cloud.google.com/docs/authentication/getting-started. Could you explain what you've done to *try* to follow those instructions? Have you created and downloaded a service file? Have you set the environment variable? (If you want to debug via VS, the easiest approach is to set it as an environment variable for your user at all times, in the Windows environment variable editor.)

**Comment by kazmi1215** [comment] 2018-10-08 16:09
Thank you so much for the quick response. I have downloaded the JSON file in my system. Now what is next step? Where I can setup my environment variable?
--> (By reading from the link) Where should I copy this line of code in my program? 
GOOGLE_APPLICATION_CREDENTIALS="C:\Users\username\Downloads\[FILE_NAME].json"

Thank you

**Comment by jskeet** [comment] 2018-10-08 16:29
It's not a line of code. You could:

- Call `Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", "...");` within your code, before doing anything else
- Use `set GOOGLE_APPLICATION_CREDENTIALS=[PATH]` on the command line, which would only set it for that command session
- Use the Windows dialog to change them for your Windows user: press the Windows key, type "environment" and select "Edit environment variables for your account"

**Comment by kazmi1215** [comment] 2018-10-08 16:38
Thank you so much. I solved it. Could you please tell me if I could limit the number of results? Like I am getting 10 12 results for every picture. Could I limit it to one?

Thank you

**Comment by jskeet** [comment] 2018-10-08 16:47
To do that, you'd have to create the `AnnotateImageRequest` request yourself, and call `client.AnnotateImage` with that.

Something like (untested):

```csharp
var request = new AnnotateImageRequest
{
    Image = Image.FromFile(...),
    Features =
    {
        new Feature { MaxResults = 1, Type = Type.Feature.Types.Type.LabelDetection }
    }
};
var response = client.AnnotateImage(request);
var labels = response.LabelAnnotations;
// Use labels
```

But you may find it simplest to just ignore all the results after the first.

I'm going to close this issue now as we're quite a long way from the original problem, which has been resolved.

**Closed by jskeet** 2018-10-08 16:47 UTC

**Comment by maheshdeshmukh22** [comment] 2019-05-08 17:09
if you are referring in java code, then you can add env variable in eclipse.
go to class contains main method -> run configurations -> Environment -> create new var and assign file path

**Comment by jskeet** [comment] 2019-05-08 17:12
@maheshdeshmukh22: No, this is .NET. But I believe the problem is resolved.

**Comment by donelpasso** [comment] 2020-02-02 08:05
This cloud SDK is absolutely awful broken piece of garbage software, google CEOs should fire everyone who was involved in "developing" this piece of crap

**Comment by udhayavardhanen** [comment] 2020-03-02 13:04
Hi,

We have downloaded the sample project from https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/vision/api 
but when we try run the application it is giving "**The Application Default Credentials are not available**". How can we sort it. please help. What are the values we have to put in .json file to set the environment variable ?

Thanks in advance!

**Comment by jskeet** [comment] 2020-03-02 13:16
@udhayavardhanen: The JSON file should be the downloaded service credentials file. You don't need to change it - just put it on disk somewhere your program can access it ,and set the GOOGLE_APPLICATION_CREDENTIALS environment variable with the fully-qualified path to the file.

**Comment by udhayavardhanen** [comment] 2020-03-02 13:21
> @udhayavardhanen: The JSON file should be the downloaded service credentials file. You don't need to change it - just put it on disk somewhere your program can access it ,and set the GOOGLE_APPLICATION_CREDENTIALS environment variable with the fully-qualified path to the file.

We are running the application in local machine now. When we move to production system can we use same json file ? also in json file there is project id and all , how to change it accordingly ?

Please help

**Comment by jskeet** [comment] 2020-03-02 13:27
You should use service account credentials that are appropriate for the Google Cloud Project you want to use to authenticate to the API servers. Typically I'd recommend using a different project for local development to production, so you can create a full test environment without any risks to production data.

**Comment by Mistic92** [comment] 2020-04-02 09:31
Hi @jskeet I'm running exact example code for Diagnostics on GKE+Istio and I'm getting this error somehow. 
```The Application Default Credentials are not available. They are available if running in Google Compute Engine.```

**Comment by amanda-tarafa** [comment] 2020-04-02 09:37
@Mistic92 This repo is part of Google client libraries as well, and we are the same maintainers here and in https://github.com/googleapis/google-cloud-dotnet.
Let's track this in googleapis/google-cloud-dotnet#4751 to have all the information in one place please.

**Comment by jskeet** [comment] 2020-04-02 09:49
I've locked the conversation on this issue as it was being used to solve all kinds of *different* scenarios. It's easiest to stick to "one scenario per issue".
If you run into problems with application credentials, and you can't find the answer in existing issues, please file a new issue at https://github.com/googleapis/google-cloud-dotnet/issues
