### ISSUE TITLE
Microsoft.Extensions.PlatformAbstractions TypeInitializationException exception

### ISSUE THREAD

**Issue by ndastur** [googleapis/gax-dotnet#231] opened 2018-01-19 09:55 UTC
Platform: Xamarin .Net project for mobile

The use of Microsoft.Extensions.PlatformAbstractions causes an exception to be thrown as per the description in this Xamarin bug report. Also includes a reproduction project.

https://bugzilla.xamarin.com/show_bug.cgi?id=60698

The PlatformAbstractions is reported as being dead. So can the replacements be substituted instead. https://github.com/aspnet/PlatformAbstractions

**Comment by craylward** [comment] 2018-01-19 18:03
Also having this issue. Incorporating Google Cloud Storage APIs and experiencing the same Syste.TypeIniailizationError.

`[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.TypeInitializationException: The type initializer for 'Google.Cloud.Storage.V1.StorageClientImpl' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.PlatformAbstractions.PlatformServices' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
[MonoDroid] Parameter name: path
[MonoDroid]   at System.IO.Path.InsecureGetFullPath (System.String path) [0x00003] in <657aa8fea4454dc898a9e5f379c58734>:0 
[MonoDroid]   at System.IO.Path.GetFullPath (System.String path) [0x00000] in <657aa8fea4454dc898a9e5f379c58734>:0 
[MonoDroid]   at Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.GetApplicationBasePath () [0x00005] in <3b3fb1475e9b464ba4578156ed96ae5e>:0 
[MonoDroid]   at Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment..ctor () [0x00000] in <3b3fb1475e9b464ba4578156ed96ae5e>:0 `

**Comment by jskeet** [comment] 2018-01-19 18:05
> So can the replacements be substituted instead. 

Not really, no. Google.Api.Gax targets netstandard1.3. It uses `Microsoft.Extensions.PlatformAbstractions.PlatformServices.Default?.Application?.RuntimeFramework?.Version`. The suggested alternatives for `RuntimeFramework` are:

- `System.Reflection.Assembly.GetEntryAssembly().GetCustomAttribute<TargetFrameworkAttribute>().FrameworkName`
- `System.AppDomain.CurrentDomain.SetupInformation.TargetFrameworkName`

Neither of these will work in netstandard1.3 as far as I'm aware.

Note that the packages that depend on GAX aren't supported on Xamarin at the moment. We'd *like* them to be at some point, but they're not at the moment.

We may need to try to work out a different workaround - although it would be nicer if the existing (meant to be GA...) package `Microsoft.Extensions.PlatformAbstractions` could be made to work on Mono.

**Comment by ndastur** [comment] 2018-01-19 18:05
If compling your own lib is an option then
```
public VersionHeaderBuilder AppendDotNetEnvironment()
              {
                     return this.AppendVersion("gl-dotnet", VersionHeaderBuilder.FormatVersion(new Version("4.6.1")));
              }
```
Will temporarly fix the problem. But this is a MASSIVE hack. It would be much better of google fixed this

**Comment by ndastur** [comment] 2018-01-19 18:09
@jskeet I believe Xamarin supports up to netstandard 1.6 so is there a possibility of not targetting 1.3?

**Comment by jskeet** [comment] 2018-01-19 18:15
No, we're not going to suddenly abandon 1.3 just because it breaks on Xamarin, which isn't a supported platform at the moment. That would be a very breaking change.

What we *could* potentially do is add support for netstandard1.5 as an extra target for this assembly, but I'd like to explore other options.

To reiterate: I would strongly advise against *trying* to use any package that uses GAX on Xamarin at the moment. We haven't tested it, and it's not a supported platform.

**Comment by ndastur** [comment] 2018-01-20 17:56
Thank you for the clarity @jskeet. I guess when people see .Net c# framework support for cloud services the assumption is there is mobile support. Very few SDKs these days for cloud services are written without thinking about mobile.
Can I just clarify another assumption? These libraries ARE the only ones to access google storage?

**Comment by jskeet** [comment] 2018-01-20 18:02
Google.Cloud.Storage.V1 is a hand-written library designed to make client code simple. It's based on Google.Apis.Storage.v1, which *doesn't* depend on GAX - so the latter *may* work for you, but it's still not *supported* on mobile.

**Comment by ndastur** [comment] 2018-01-22 14:55
@jskeet thank you for all your input. I think for the moment we have to assume Xamarin is an unsupported platform and so can't really use it in production code. Do let us know if Google plans support for Xamarin .Net. We'd be happy to beta test

**Comment by jskeet** [comment] 2018-06-04 07:49
Closing this now, as it's about an unsupported platform.

**Comment by tadeuszwojcik** [comment] 2019-01-31 12:43
Hi,
I've recently tried using `Google.Cloud.Storage` and `OpenCensus` libs, both of which use this lib under the hood and both of them throw the same exception as described in this issue. I'm using .NET Core 3 Preview 2 (console app) so I guess it's the reason why it didn't came up sooner. Would it be possible to add try catch around call to `Microsoft.Extensions.PlatformAbstractions.PlatformServices` given it's depreciated and not supported lib anymore? I could also downgrade to v2.2 but I think when .NET Core 3 get released, it will become and issue again.
Thanks.

Error details:
```
  exception:  "System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.PlatformAbstractions.PlatformServices' threw an exception. ---> System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.GetEntryAssembly()
   at Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment..ctor()
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices..ctor()
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_Default()
   at Google.Api.Gax.VersionHeaderBuilder.AppendDotNetEnvironment()
   at Google.Api.Gax.Grpc.ServiceSettingsBase..ctor()
```

**Comment by jskeet** [comment] 2019-01-31 17:10
@tadeuszwojcik: Thanks for the update. I wasn't aware this was broken in .NET Core 3.0 preview, although that's a really weird exception for it to throw. It surprises me, and it may not be deliberate - normally even deprecated methods are still expected to work.

I have preview 2 installed myself, so next week (when I'm back at my desk instead of at a conference) I'll try to reproduce this (which should be easy) and we can work out what to do.

**Comment by tadeuszwojcik** [comment] 2019-02-01 16:55
Great, thank you, really appreciate that! If you'd have trouble reproducing that, please let me know, I'll try to come up with simple reproducible repo.

**Comment by jskeet** [comment] 2019-02-04 08:17
Okay, I've reproduced it now. I would really hope .NET Core 3.0 *won't* behave exactly like this - I'll file an issue in corefx (if there isn't one already) but we should probably look at alternatives anyway. The problem comes if there's no alternative that's available on the platforms we target...

**Comment by jskeet** [comment] 2019-02-04 08:36
Filed https://github.com/dotnet/corefx/issues/35068

We can parse the result of `System.Reflection.Assembly.GetEntryAssembly().GetCustomAttribute<TargetFrameworkAttribute>().FrameworkName` instead - which may well still not work on Xamarin, of course, but should at least work on .NET Core 3.0...

**Comment by tadeuszwojcik** [comment] 2019-02-05 07:48
Thanks for looking into that issue and finding root cause, really appreciate it.

**Closed** 2019-02-05 09:08 UTC
Labels: :rotating_light:, Priority: P2+, Type: bug
